-- GUÍAS DETALLADAS POR MATERIALES (PROFUNDIZACIÓN)
INSERT INTO contenidos_estaticos (titulo, cuerpo, tipo, autor) VALUES 
('Identificación de Plásticos: El Triángulo de Möbius', 'Aprende a identificar qué compras:\n1. PET: Botellas de bebidas. Muy reciclable.\n2. PEAD: Envases de leche y detergentes. Muy reciclable.\n3. PVC: Tuberías, mangueras. Difícil de reciclar, evitar si es posible.\n4. PEBD: Bolsas de súper, film transparente. Reciclable si está limpio.\n5. PP: Tapas de botellas, popotes, recipientes de yogurt. Reciclable.\n6. PS: Unicel, platos desechables. Altamente contaminante, poco reciclable.\n7. Otros: Mezclas de resinas. Generalmente no se recicla.', 'GUIA', 'Experto Ambiental'),
('Residuos de Manejo Especial: Pilas y Baterías', 'NUNCA tires las pilas a la basura común. Una sola pila de botón puede contaminar 600,000 litros de agua. \nInstrucciones: \n1. Cubre los polos con cinta adhesiva. \n2. Almacénalas en botellas de plástico secas. \n3. Llévalas a centros de acopio específicos o columnas de recolección urbana.', 'GUIA', 'Manual de Clasificación'),
('Aceite de Cocina Usado: No lo tires al drenaje', 'Un litro de aceite contamina 1,000 litros de agua y tapa las tuberías.\nCómo manejarlo:\n1. Deja enfriar el aceite.\n2. Fíltralo con un colador para quitar restos de comida.\n3. Viértelo en una botella de plástico con tapa.\n4. Busca un centro que lo transforme en Biodiésel o jabón.', 'GUIA', 'Guía de Residuos Urbanos'),
('Residuos Electrónicos (E-Waste)', 'Celulares, cables y computadoras contienen metales pesados como plomo y cadmio.\nRecomendación:\n1. Borra tu información personal.\n2. No intentes desarmarlos (pueden liberar gases tóxicos).\n3. Llévalos a "Reciclatrones" o campañas especiales de recolección electrónica.', 'GUIA', 'Secretaría de Medio Ambiente');

-- TIPS CORTOS Y DATOS CURIOSOS (INVESTIGACIÓN)
INSERT INTO contenidos_estaticos (titulo, cuerpo, tipo, autor) VALUES 
('Dato Eco: El ahorro del Aluminio', 'Reciclar una lata de aluminio ahorra el 95% de la energía necesaria para fabricar una nueva desde cero. ¡Con esa energía podrías mantener encendida una televisión por 3 horas!', 'TIP', 'EcoInvestigador'),
('Dato Eco: Degradación del Plástico', 'Una botella de plástico PET tarda hasta 500 años en degradarse. Si la reciclas, en 60 días puede volver a estar en el estante como un producto nuevo.', 'TIP', 'EcoInvestigador'),
('Tip: Compra Inteligente', 'El mejor residuo es el que no se genera. Prefiere productos con menos empaques o envases retornables de vidrio.', 'TIP', 'EducBot'),
('Tip: Las servilletas no son papel', 'Las servilletas de papel usadas, pañuelos desechables y papel higiénico NO entran en la categoría de papel reciclable. Van directamente a la basura general o composta si están libres de químicos.', 'TIP', 'EducBot'),
('Tip: Tapitas que salvan vidas', 'Juntar las tapas de plástico (PP) no solo ayuda al reciclaje, sino que muchas organizaciones las utilizan para costear tratamientos de quimioterapia para niños. ¡No las tires!', 'TIP', 'EducBot');

-- ARTÍCULOS EDUCATIVOS (EXTENSOS)
INSERT INTO contenidos_estaticos (titulo, cuerpo, tipo, autor) VALUES 
('El Proceso del Compostaje Casero', 'El compostaje es el proceso natural de descomposición de la materia orgánica. \nPara empezar necesitas:\n1. Un contenedor con ventilación.\n2. Materia Verde (Nitrógeno): Restos de frutas, verduras, café.\n3. Materia Café (Carbono): Hojas secas, cartón picado, aserrín.\nEl secreto es el equilibrio: 2 partes de café por 1 de verde. Mantén la humedad como una esponja escurrida y en 3 meses tendrás abono para tus plantas.', 'ARTICULO', 'Especialista en Composta'),
('¿Qué es la Economía Circular?', 'A diferencia del modelo lineal (extraer, fabricar, desechar), la economía circular propone un ciclo donde los materiales se mantienen en uso la mayor parte del tiempo. Se basa en tres principios: eliminar residuos desde el diseño, mantener productos en uso y regenerar sistemas naturales. Al reciclar, tú eres una pieza clave de este cambio global.', 'ARTICULO', 'Alianza Ambiental'),
('Fast Fashion: El costo de la ropa barata', 'La industria textil es la segunda más contaminante del mundo. Se necesitan 2,700 litros de agua para fabricar una sola camiseta de algodón. \nAlternativas:\n1. Compra ropa de segunda mano.\n2. Prefiere fibras naturales como lino o algodón orgánico.\n3. Repara tus prendas antes de desecharlas.', 'ARTICULO', 'Moda Sustentable'),
('Microplásticos: La amenaza invisible', 'Los microplásticos son partículas menores a 5mm que ya se encuentran en nuestra comida, agua y aire. Provienen de la degradación de plásticos grandes y del lavado de ropa sintética. Reducir nuestro consumo de plásticos de un solo uso es la única forma de frenar esta invasión en nuestra cadena alimenticia.', 'ARTICULO', 'Ciencia Ambiental');
